name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git Semantic Verison
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern: 'major:'
          minor_pattern: 'minor:'
          format: '${major}.${minor}.${patch}-prerelease${increment}'
        id: version

      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          NEW_VERSION: ${{steps.version.outputs.version}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "NEW VERSION: $NEW_VERSION"
      # - name: Build Docker Image
      #   run: |
      #     echo "Inciando docker build"
      #     docker build -t serv1008/docker-graphql:0.0.2 .
      #     echo "Fin docker build"
      # - name: Push Docker Image
      #   run: |
      #     echo "Inciando docker push"
      #     docker push serv1008/docker-graphql:0.0.2
      #     echo "Fin docker push"
