name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          echo "Inciando docker login"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Fin docker login"
      - name: Build Docker Image
        run: |
          echo "Inciando docker build"
          docker build -t serv1008/docker-graphql:0.0.2 .
          echo "Fin docker build"
      - name: Push Docker Image
        run: |
          echo "Inciando docker push"
          docker push serv1008/docker-graphql:0.0.2
          echo "Fin docker push"
